# Generated by Django 4.0.2 on 2022-02-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PATIENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('ml', 'Male'), ('fl', 'Female'), ('nb', 'Others')], max_length=2)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_no', models.IntegerField()),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('method', models.CharField(choices=[('CSH', 'Cash'), ('BKS', 'Bkash'), ('NGD', 'Nagad'), ('RKT', 'Rocket'), ('CRD', 'Card')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='APPOINTMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.payment')),
            ],
        ),
    ]
